package com.soundly.data.model

import android.net.Uri
import androidx.compose.runtime.Immutable

@Immutable
data class Playlist(
    val id: String,
    val name: String,
    val songCount: Int,
    val isAutoGenerated: Boolean,
    val artworkUri: Uri? = null,
    val showOnHome: Boolean = false,
    val updatedAt: Long = 0L
)

@Immutable
data class FolderSummary(
    val path: String,
    val name: String,
    val songCount: Int
)

@Immutable
data class LibraryCatalog(
    val songs: List<Song>,
    val songsByAlbumId: Map<Long, List<Song>>,
    val songsByArtistId: Map<Long, List<Song>>, // 👈 Nuevo: Soporte para múltiples artistas
    val artistPrimaryAlbumId: Map<Long, Long>,
    val albums: List<Album>,
    val artists: List<Artist>,
    val folders: List<FolderSummary>
)

fun buildLibraryCatalog(songs: List<Song>): LibraryCatalog {
    if (songs.isEmpty()) {
        return LibraryCatalog(
            songs = emptyList(),
            songsByAlbumId = emptyMap(),
            songsByArtistId = emptyMap(),
            artistPrimaryAlbumId = emptyMap(),
            albums = emptyList(),
            artists = emptyList(),
            folders = emptyList()
        )
    }

    val groupedByAlbum = songs.groupBy { it.albumId }
    val groupedByFolder = songs.groupBy { it.path.folderPath() }

    // Sistema inteligente de artistas: una canción puede pertenecer a varios artistas
    val songsByArtistId = mutableMapOf<Long, MutableList<Song>>()
    val artistNameMap = mutableMapOf<Long, String>()

    songs.forEach { song ->
        val names = song.artistNames
        names.forEach { name ->
            val id = generateArtistId(name)
            songsByArtistId.getOrPut(id) { mutableListOf() }.add(song)
            artistNameMap[id] = name
        }
    }

    val albums = groupedByAlbum
        .values
        .map { albumSongs ->
            val first = albumSongs.first()
            Album(
                id = first.albumId,
                name = first.album,
                artist = first.artist,
                songCount = albumSongs.size
            )
        }
        .sortedBy { it.name.lowercase() }

    val artists = songsByArtistId
        .map { (id, artistSongs) ->
            val artistName = artistNameMap[id] ?: "Unknown Artist"
            val primaryAlbumId = artistSongs.firstOrNull()?.albumId
            Artist(
                id = id,
                name = artistName,
                songCount = artistSongs.size,
                albumCount = artistSongs.map { it.albumId }.distinct().size,
                artworkUri = primaryAlbumId?.let { albumId ->
                    android.content.ContentUris.withAppendedId(
                        android.net.Uri.parse("content://media/external/audio/albumart"),
                        albumId
                    )
                }
            )
        }
        .sortedBy { it.name.lowercase() }

    val artistPrimaryAlbumId = songsByArtistId
        .mapNotNull { (artistId, artistSongs) ->
            artistSongs.firstOrNull()?.albumId?.let { artistId to it }
        }
        .toMap()

    val folders = groupedByFolder
        .map { (path, folderSongs) ->
            FolderSummary(
                path = path,
                name = path.substringAfterLast('/').ifBlank { path },
                songCount = folderSongs.size
            )
        }
        .sortedBy { it.name.lowercase() }

    return LibraryCatalog(
        songs = songs,
        songsByAlbumId = groupedByAlbum,
        songsByArtistId = songsByArtistId,
        artistPrimaryAlbumId = artistPrimaryAlbumId,
        albums = albums,
        artists = artists,
        folders = folders
    )
}

private fun String.folderPath(): String {
    val normalized = replace('\\', '/')
    return normalized.substringBeforeLast('/', missingDelimiterValue = normalized)
}
