package com.soundly.data.model

import android.net.Uri

data class Playlist(
    val id: String,
    val name: String,
    val songCount: Int,
    val isAutoGenerated: Boolean,
    val artworkUri: Uri? = null,
    val updatedAt: Long = 0L
)

data class FolderSummary(
    val path: String,
    val name: String,
    val songCount: Int
)

data class LibraryCatalog(
    val songs: List<Song>,
    val songsByAlbumId: Map<Long, List<Song>>,
    val artistPrimaryAlbumId: Map<Long, Long>,
    val albums: List<Album>,
    val artists: List<Artist>,
    val folders: List<FolderSummary>
)

fun buildLibraryCatalog(songs: List<Song>): LibraryCatalog {
    val groupedByAlbum = songs.groupBy { it.albumId }
    val groupedByArtist = songs.groupBy { it.artistId }
    val groupedByFolder = songs.groupBy { it.path.folderPath() }

    val albums = groupedByAlbum
        .values
        .map { albumSongs ->
            val first = albumSongs.first()
            Album(
                id = first.albumId,
                name = first.album,
                artist = first.artist,
                songCount = albumSongs.size
            )
        }
        .sortedBy { it.name.lowercase() }

    val artists = groupedByArtist
        .values
        .map { artistSongs ->
            val first = artistSongs.first()
            Artist(
                id = first.artistId,
                name = first.artist,
                songCount = artistSongs.size,
                albumCount = artistSongs.map { it.albumId }.distinct().size
            )
        }
        .sortedBy { it.name.lowercase() }

    val artistPrimaryAlbumId = groupedByArtist
        .mapNotNull { (artistId, artistSongs) ->
            artistSongs.firstOrNull()?.albumId?.let { artistId to it }
        }
        .toMap()

    val folders = groupedByFolder
        .map { (path, folderSongs) ->
            FolderSummary(
                path = path,
                name = path.substringAfterLast('/').ifBlank { path },
                songCount = folderSongs.size
            )
        }
        .sortedBy { it.name.lowercase() }

    return LibraryCatalog(
        songs = songs,
        songsByAlbumId = groupedByAlbum,
        artistPrimaryAlbumId = artistPrimaryAlbumId,
        albums = albums,
        artists = artists,
        folders = folders
    )
}

private fun String.folderPath(): String {
    val normalized = replace('\\', '/')
    return normalized.substringBeforeLast('/', missingDelimiterValue = normalized)
}
