package com.soundly.ui.componentes

import android.net.Uri
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.rounded.ArrowBack
import androidx.compose.material.icons.automirrored.rounded.KeyboardArrowRight
import androidx.compose.material.icons.automirrored.rounded.PlaylistAdd
import androidx.compose.material.icons.automirrored.rounded.QueueMusic
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage
import coil.request.ImageRequest
import com.soundly.R
import com.soundly.data.model.Playlist
import com.soundly.data.model.Song

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PlaylistOptionsSheet(
    playlist: Playlist,
    songs: List<Song>,
    artUri: Uri?,
    userPlaylists: List<Playlist>,
    onDismissRequest: () -> Unit,
    onPlayNext: () -> Unit,
    onAddToQueue: () -> Unit,
    onTransferToPlaylist: (String) -> Unit,
    onExportClick: (String) -> Unit,
    onSaveAsPlaylist: () -> Unit = {}
) {
    var sheetMode by remember { mutableStateOf(PlaylistSheetMode.MAIN) }

    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val subSheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)

    if (sheetMode == PlaylistSheetMode.MAIN) {
        ModalBottomSheet(
            onDismissRequest = onDismissRequest,
            sheetState = sheetState,
            containerColor = MaterialTheme.colorScheme.surface,
            scrimColor = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.32f),
            shape = RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp),
            dragHandle = {
                Box(
                    modifier = Modifier
                        .padding(vertical = 12.dp)
                        .size(width = 36.dp, height = 4.dp)
                        .clip(CircleShape)
                        .background(MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.3f))
                )
            }
        ) {
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 24.dp)
            ) {
                item {
                    PlaylistSheetHeader(playlist = playlist, artUri = artUri, onClose = onDismissRequest)
                }

                item {
                    HorizontalDivider(
                        modifier = Modifier.padding(horizontal = 20.dp, vertical = 8.dp),
                        color = MaterialTheme.colorScheme.outline.copy(alpha = 0.5f)
                    )
                }

                item {
                    QuickActionsRow(
                        onPlayNext = { onDismissRequest(); onPlayNext() },
                        onAddToQueue = { onDismissRequest(); onAddToQueue() }
                    )
                }

                item {
                    Spacer(modifier = Modifier.height(8.dp))
                    HorizontalDivider(
                        modifier = Modifier.padding(horizontal = 20.dp, vertical = 4.dp),
                        color = MaterialTheme.colorScheme.outline.copy(alpha = 0.3f)
                    )
                }

                if (playlist.isAutoGenerated) {
                    item {
                        MenuItemWithIcon(
                            text = stringResource(R.string.menu_save_as_playlist),
                            icon = Icons.Rounded.PlaylistAddCheck,
                            onClick = { onDismissRequest(); onSaveAsPlaylist() }
                        )
                    }
                }

                item {
                    MenuItemWithIcon(
                        text = stringResource(R.string.menu_transfer_playlist),
                        icon = Icons.AutoMirrored.Rounded.PlaylistAdd,
                        onClick = { sheetMode = PlaylistSheetMode.TRANSFER }
                    )
                }

                item {
                    MenuItemWithIcon(
                        text = stringResource(R.string.menu_export_playlist),
                        icon = Icons.Rounded.IosShare,
                        onClick = { sheetMode = PlaylistSheetMode.EXPORT_SELECT_FORMAT }
                    )
                }
            }
        }
    } else if (sheetMode == PlaylistSheetMode.TRANSFER) {
        ModalBottomSheet(
            onDismissRequest = { sheetMode = PlaylistSheetMode.MAIN },
            sheetState = subSheetState,
            containerColor = MaterialTheme.colorScheme.surface,
            scrimColor = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.32f),
            shape = RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp),
            dragHandle = {
                Box(
                    modifier = Modifier
                        .padding(vertical = 12.dp)
                        .size(width = 36.dp, height = 4.dp)
                        .clip(CircleShape)
                        .background(MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.3f))
                )
            }
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 20.dp, vertical = 8.dp)
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    IconButton(onClick = { sheetMode = PlaylistSheetMode.MAIN }) {
                        Icon(Icons.AutoMirrored.Rounded.ArrowBack, null)
                    }
                    Text(
                        text = stringResource(R.string.menu_transfer_playlist_title),
                        style = MaterialTheme.typography.headlineSmall,
                        color = MaterialTheme.colorScheme.onSurface,
                        fontWeight = FontWeight.Bold
                    )
                }
                Spacer(modifier = Modifier.height(16.dp))

                val otherPlaylists = userPlaylists.filter { it.id != playlist.id }

                if (otherPlaylists.isEmpty()) {
                    Text(
                        text = stringResource(R.string.menu_no_playlists),
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        modifier = Modifier.padding(bottom = 20.dp)
                    )
                } else {
                    LazyColumn(
                        verticalArrangement = Arrangement.spacedBy(6.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        items(otherPlaylists, key = { it.id }) { targetPlaylist ->
                            TransferPlaylistItem(
                                playlist = targetPlaylist,
                                onClick = {
                                    onTransferToPlaylist(targetPlaylist.id)
                                    onDismissRequest()
                                }
                            )
                        }
                    }
                }
                Spacer(modifier = Modifier.height(24.dp))
            }
        }
    } else if (sheetMode == PlaylistSheetMode.EXPORT_SELECT_FORMAT) {
        ModalBottomSheet(
            onDismissRequest = { sheetMode = PlaylistSheetMode.MAIN },
            sheetState = subSheetState,
            containerColor = MaterialTheme.colorScheme.surface,
            scrimColor = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.32f),
            shape = RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp),
            dragHandle = {
                Box(
                    modifier = Modifier
                        .padding(vertical = 12.dp)
                        .size(width = 36.dp, height = 4.dp)
                        .clip(CircleShape)
                        .background(MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.3f))
                )
            }
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp, vertical = 8.dp)
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    IconButton(onClick = { sheetMode = PlaylistSheetMode.MAIN }) {
                        Icon(Icons.AutoMirrored.Rounded.ArrowBack, null)
                    }
                    Text(
                        text = stringResource(R.string.export_info_title),
                        style = MaterialTheme.typography.headlineSmall,
                        color = MaterialTheme.colorScheme.onSurface,
                        fontWeight = FontWeight.Bold
                    )
                }
                
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    text = stringResource(R.string.export_info_desc),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                
                Spacer(modifier = Modifier.height(24.dp))

                FormatSelectionItem(
                    title = "M3U",
                    description = stringResource(R.string.format_m3u_desc),
                    onClick = {
                        onDismissRequest()
                        onExportClick("m3u")
                    }
                )
                
                Spacer(modifier = Modifier.height(12.dp))

                FormatSelectionItem(
                    title = "M3U8",
                    description = stringResource(R.string.format_m3u8_desc),
                    onClick = {
                        onDismissRequest()
                        onExportClick("m3u8")
                    }
                )

                Spacer(modifier = Modifier.height(12.dp))

                FormatSelectionItem(
                    title = "XSPF",
                    description = stringResource(R.string.format_xspf_desc),
                    onClick = {
                        onDismissRequest()
                        onExportClick("xspf")
                    }
                )
                
                Spacer(modifier = Modifier.height(32.dp))
            }
        }
    }
}

private enum class PlaylistSheetMode {
    MAIN, TRANSFER, EXPORT_SELECT_FORMAT
}

@Composable
private fun FormatSelectionItem(
    title: String,
    description: String,
    onClick: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(20.dp))
            .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
            .clickable(onClick = onClick)
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Box(
            modifier = Modifier
                .size(48.dp)
                .clip(CircleShape)
                .background(MaterialTheme.colorScheme.primary.copy(alpha = 0.1f)),
            contentAlignment = Alignment.Center
        ) {
            Icon(
                imageVector = Icons.Rounded.Description,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.primary
            )
        }
        Spacer(modifier = Modifier.width(16.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = title,
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onSurface
            )
            Text(
                text = description,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
        Icon(
            imageVector = Icons.AutoMirrored.Rounded.KeyboardArrowRight,
            contentDescription = null,
            tint = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f)
        )
    }
}

@Composable
private fun PlaylistSheetHeader(playlist: Playlist, artUri: Uri?, onClose: () -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(start = 20.dp, end = 12.dp, top = 4.dp, bottom = 4.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Box(
            modifier = Modifier
                .size(62.dp)
                .clip(RoundedCornerShape(14.dp))
                .background(MaterialTheme.colorScheme.surfaceVariant),
            contentAlignment = Alignment.Center
        ) {
            AsyncImage(
                model = ImageRequest.Builder(LocalContext.current)
                    .data(artUri ?: R.drawable.playlist_favicon)
                    .crossfade(true)
                    .allowHardware(true)
                    .build(),
                contentDescription = playlist.name,
                contentScale = ContentScale.Crop,
                modifier = Modifier.matchParentSize(),
                placeholder = painterResource(R.drawable.playlist_favicon),
                error = painterResource(R.drawable.playlist_favicon)
            )
        }
        Spacer(modifier = Modifier.size(14.dp))
        Column(modifier = Modifier.weight(1f)) {
            val playlistName = if (playlist.id == com.soundly.data.repository.MusicRepository.LIKED_SONGS_PLAYLIST_ID) {
                stringResource(R.string.liked_songs_title)
            } else {
                playlist.name
            }
            Text(text = playlistName, style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.onSurface, maxLines = 1, overflow = TextOverflow.Ellipsis)
            Text(text = stringResource(R.string.songs_count, playlist.songCount), style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, maxLines = 1, overflow = TextOverflow.Ellipsis)
            Spacer(modifier = Modifier.height(6.dp))
            Surface(
                color = MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.6f),
                shape = RoundedCornerShape(50),
                modifier = Modifier.height(20.dp)
            ) {
                Text(
                    text = if (playlist.isAutoGenerated) stringResource(R.string.library_auto_collection) else stringResource(R.string.library_label_playlist),
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onSecondaryContainer,
                    modifier = Modifier.padding(horizontal = 8.dp, vertical = 2.dp)
                )
            }
        }
        IconButton(
            onClick = onClose,
            modifier = Modifier.size(36.dp).clip(CircleShape)
        ) {
            Icon(imageVector = Icons.Rounded.Close, contentDescription = stringResource(R.string.cd_close), modifier = Modifier.size(18.dp))
        }
    }
}

@Composable
private fun QuickActionsRow(
    onPlayNext: () -> Unit,
    onAddToQueue: () -> Unit
) {
    Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 20.dp, vertical = 8.dp), horizontalArrangement = Arrangement.spacedBy(10.dp)) {
        QuickActionChip(label = stringResource(R.string.quick_action_play_next), icon = Icons.Rounded.PlayArrow, modifier = Modifier.weight(1f), onClick = onPlayNext)
        QuickActionChip(label = stringResource(R.string.quick_action_in_queue), icon = Icons.AutoMirrored.Rounded.QueueMusic, modifier = Modifier.weight(1f), onClick = onAddToQueue)
    }
}

@Composable
private fun QuickActionChip(label: String, icon: ImageVector, modifier: Modifier = Modifier, onClick: () -> Unit) {
    Column(
        modifier = modifier
            .height(72.dp)
            .clip(RoundedCornerShape(16.dp))
            .background(MaterialTheme.colorScheme.surfaceVariant)
            .clickable(onClick = onClick)
            .padding(horizontal = 4.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Icon(imageVector = icon, contentDescription = label, tint = MaterialTheme.colorScheme.onSurface, modifier = Modifier.size(22.dp))
        Spacer(Modifier.height(4.dp))
        Text(text = label, style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurface, maxLines = 1, overflow = TextOverflow.Ellipsis)
    }
}

@Composable
private fun MenuItemWithIcon(text: String, icon: ImageVector, onClick: () -> Unit) {
    Row(modifier = Modifier.fillMaxWidth().clickable(onClick = onClick).padding(horizontal = 20.dp, vertical = 14.dp), verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(16.dp)) {
        Icon(imageVector = icon, contentDescription = null, tint = MaterialTheme.colorScheme.onSurface, modifier = Modifier.size(22.dp))
        Text(text = text, style = MaterialTheme.typography.bodyLarge, color = MaterialTheme.colorScheme.onSurface)
    }
}

@Composable
private fun TransferPlaylistItem(playlist: Playlist, onClick: () -> Unit) {
    Row(
        modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(14.dp)).background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.6f)).clickable(onClick = onClick).padding(12.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Box(modifier = Modifier.size(42.dp).clip(RoundedCornerShape(12.dp)).background(MaterialTheme.colorScheme.onSurface.copy(alpha = 0.08f)), contentAlignment = Alignment.Center) {
            AsyncImage(
                model = ImageRequest.Builder(LocalContext.current)
                    .data(playlist.artworkUri ?: R.drawable.playlist_favicon)
                    .crossfade(true)
                    .allowHardware(true)
                    .build(),
                contentDescription = null,
                contentScale = ContentScale.Crop,
                modifier = Modifier.matchParentSize(),
                placeholder = painterResource(R.drawable.playlist_favicon),
                error = painterResource(R.drawable.playlist_favicon)
            )
        }
        Spacer(modifier = Modifier.size(12.dp))
        Column(modifier = Modifier.weight(1f)) {
            val playlistName = if (playlist.id == com.soundly.data.repository.MusicRepository.LIKED_SONGS_PLAYLIST_ID) {
                stringResource(R.string.liked_songs_title)
            } else {
                playlist.name
            }
            Text(text = playlistName, style = MaterialTheme.typography.titleSmall, color = MaterialTheme.colorScheme.onSurface, maxLines = 1, overflow = TextOverflow.Ellipsis)
            Text(text = stringResource(R.string.playlist_item_add_here), style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
    }
}
