package com.soundly.data.repository

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.database.ContentObserver
import android.net.Uri
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.provider.MediaStore
import androidx.core.content.ContextCompat
import androidx.room.withTransaction
import com.soundly.data.datasource.MediaStoreDataSource
import com.soundly.data.local.FavoriteAlbumEntity
import com.soundly.data.local.FavoriteArtistEntity
import com.soundly.data.local.FavoriteSongEntity
import com.soundly.data.local.LibraryMetadataDao
import com.soundly.data.local.PlayHistoryEntity
import com.soundly.data.local.PlaylistEntity
import com.soundly.data.local.PlaylistSongEntity
import com.soundly.data.local.SongCacheDao
import com.soundly.data.local.SoundlyDatabase
import com.soundly.data.local.mapper.toDomain
import com.soundly.data.local.mapper.toEntity
import com.soundly.data.model.Album
import com.soundly.data.model.Artist
import com.soundly.data.model.MusicScanFilters
import com.soundly.data.model.MusicScanReport
import com.soundly.data.model.Playlist
import com.soundly.data.model.Song
import com.soundly.inicio.data.MediaScannerPreferences
import com.soundly.inicio.data.MediaScannerSettings
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.File
import java.util.UUID
import javax.inject.Inject

class MusicRepository @Inject constructor(
    private val mediaStore: MediaStoreDataSource,
    private val songCacheDao: SongCacheDao,
    private val libraryMetadataDao: LibraryMetadataDao,
    private val database: SoundlyDatabase,
    @ApplicationContext private val context: Context
) {
    private val librarySongs = MutableStateFlow<List<Song>>(emptyList())
    private val lastScannedSourceSongs = MutableStateFlow<List<Song>>(emptyList())
    private val favoriteSongIds = MutableStateFlow<Set<Long>>(emptySet())
    private val favoriteAlbumIds = MutableStateFlow<Set<Long>>(emptySet())
    private val favoriteArtistIds = MutableStateFlow<Set<Long>>(emptySet())
    private val playlistEntities = MutableStateFlow<List<PlaylistEntity>>(emptyList())
    private val playlistSongEntities = MutableStateFlow<List<PlaylistSongEntity>>(emptyList())
    private val playlists = MutableStateFlow<List<Playlist>>(emptyList())
    private val _lastScanReport = MutableStateFlow<MusicScanReport?>(null)
    val lastScanReport: StateFlow<MusicScanReport?> = _lastScanReport.asStateFlow()
    val librarySongsFlow: StateFlow<List<Song>> = librarySongs.asStateFlow()
    val favoriteSongIdsFlow: StateFlow<Set<Long>> = favoriteSongIds.asStateFlow()
    val favoriteAlbumIdsFlow: StateFlow<Set<Long>> = favoriteAlbumIds.asStateFlow()
    val favoriteArtistIdsFlow: StateFlow<Set<Long>> = favoriteArtistIds.asStateFlow()
    val playlistsFlow: StateFlow<List<Playlist>> = playlists.asStateFlow()
    val userPlaylistsFlow: Flow<List<Playlist>> = playlistsFlow.map { current ->
        current.filterNot(Playlist::isAutoGenerated)
    }
    val playlistMembershipBySongFlow: Flow<Map<Long, Set<String>>> = playlistSongEntities.asStateFlow().map { entries ->
        entries.groupBy { it.songId }
            .mapValues { (_, songEntries) ->
                songEntries.asSequence()
                    .map { it.playlistId }
                    .toSet()
            }
    }

    private val repositoryScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val refreshMutex = Mutex()
    @Volatile
    private var cacheBootstrapDone = false
    @Volatile
    private var mediaStoreSyncDone = false
    private var mediaStoreObserver: ContentObserver? = null
    private var pendingRefreshJob: Job? = null

    init {
        observeLocalCache()
        observeLibraryMetadata()
        registerMediaStoreObserver()
        repositoryScope.launch {
            bootstrapFromLocalCache()
            refreshLibrarySongs(force = true)
        }
    }

    suspend fun getSongs(): List<Song> = withContext(Dispatchers.IO) {
        mediaStore.getSongs()
    }

    suspend fun getSongsForLibrary(): List<Song> = withContext(Dispatchers.IO) {
        ensureLibrarySongsLoaded()
        librarySongs.value
    }

    suspend fun scanSongs(
        ignoreTempFolders: Boolean,
        ignoreShortAudios: Boolean,
        manuallyBlockedFolders: Set<String> = emptySet(),
        manuallyBlockedSongIds: Set<Long> = emptySet(),
        onDiscoveredBatch: suspend (List<String>) -> Unit
    ): MusicScanReport = withContext(Dispatchers.IO) {
        val imported = mutableListOf<Song>()
        val scannedSource = mutableListOf<Song>()
        val discoveredBatch = mutableListOf<String>()
        var blockedByTemp = 0
        var blockedByShort = 0
        var scannedCount = 0

        mediaStore.streamSongs { song ->
            scannedCount++
            scannedSource.add(song)
            discoveredBatch.add(song.title.ifBlank { "(Sin nombre)" })

            val blockedTemp = ignoreTempFolders && song.path.isTempFolderPath()
            val blockedShort = ignoreShortAudios && song.duration < MIN_AUDIO_DURATION_MS
            val blockedManualFolder = manuallyBlockedFolders.contains(song.folderPath())
            val blockedManualSong = manuallyBlockedSongIds.contains(song.id)
            val blocked = blockedTemp || blockedShort || blockedManualFolder || blockedManualSong

            if (blockedTemp) blockedByTemp++
            if (blockedShort) blockedByShort++
            if (!blocked) imported.add(song)

            if (discoveredBatch.size >= DISCOVERY_BATCH_SIZE) {
                val batch = discoveredBatch.toList()
                discoveredBatch.clear()
                runBlocking { onDiscoveredBatch(batch) }
            }
        }

        if (discoveredBatch.isNotEmpty()) {
            onDiscoveredBatch(discoveredBatch.toList())
        }

        MediaScannerPreferences.saveSettings(
            context = context,
            settings = MediaScannerSettings(
                ignoreTempFolders = ignoreTempFolders,
                ignoreShortAudios = ignoreShortAudios,
                blockedFolders = manuallyBlockedFolders,
                blockedSongIds = manuallyBlockedSongIds
            )
        )

        lastScannedSourceSongs.value = scannedSource
        syncSongsIncrementally(imported)
        mediaStoreSyncDone = true

        val report = MusicScanReport(
            scannedSongs = scannedCount,
            importedSongs = imported.size,
            blockedSongs = scannedCount - imported.size,
            blockedByTempFolders = blockedByTemp,
            blockedByShortDuration = blockedByShort,
            activeFilters = MusicScanFilters(
                ignoreTempFolders = ignoreTempFolders,
                ignoreShortAudios = ignoreShortAudios
            )
        )
        _lastScanReport.value = report
        report
    }

    suspend fun getCurrentScannerSettings(): MediaScannerSettings = withContext(Dispatchers.IO) {
        MediaScannerPreferences.getSettings(context)
    }

    suspend fun setScanConfirmed(confirmed: Boolean) = withContext(Dispatchers.IO) {
        MediaScannerPreferences.setScanConfirmed(context, confirmed)
    }

    suspend fun isScanConfirmed(): Boolean = withContext(Dispatchers.IO) {
        MediaScannerPreferences.isScanConfirmed(context)
    }

    suspend fun getAlbums(): List<Album> = withContext(Dispatchers.IO) {
        mediaStore.getAlbums()
    }

    suspend fun getArtists(): List<Artist> = withContext(Dispatchers.IO) {
        mediaStore.getArtists()
    }

    fun getAlbumArtUri(albumId: Long): Uri {
        return mediaStore.getAlbumArtUri(albumId)
    }

    fun isSongFavorite(songId: Long): Boolean = favoriteSongIds.value.contains(songId)

    fun isAlbumFavorite(albumId: Long): Boolean = favoriteAlbumIds.value.contains(albumId)

    fun isArtistFavorite(artistId: Long): Boolean = favoriteArtistIds.value.contains(artistId)

    suspend fun toggleSongFavorite(songId: Long): Boolean = withContext(Dispatchers.IO) {
        database.withTransaction {
            val isFavorite = libraryMetadataDao.isSongFavorite(songId)
            val now = System.currentTimeMillis()
            if (isFavorite) {
                libraryMetadataDao.deleteFavoriteSong(songId)
            } else {
                ensureLikedSongsPlaylist(now)
                libraryMetadataDao.upsertFavoriteSong(
                    FavoriteSongEntity(songId = songId, createdAt = now)
                )
            }
            libraryMetadataDao.touchPlaylist(LIKED_SONGS_PLAYLIST_ID, now)
            !isFavorite
        }
    }

    suspend fun toggleAlbumFavorite(albumId: Long): Boolean = withContext(Dispatchers.IO) {
        database.withTransaction {
            val isFavorite = libraryMetadataDao.isAlbumFavorite(albumId)
            if (isFavorite) {
                libraryMetadataDao.deleteFavoriteAlbum(albumId)
            } else {
                libraryMetadataDao.upsertFavoriteAlbum(
                    FavoriteAlbumEntity(
                        albumId = albumId,
                        createdAt = System.currentTimeMillis()
                    )
                )
            }
            !isFavorite
        }
    }

    suspend fun toggleArtistFavorite(artistId: Long): Boolean = withContext(Dispatchers.IO) {
        database.withTransaction {
            val isFavorite = libraryMetadataDao.isArtistFavorite(artistId)
            if (isFavorite) {
                libraryMetadataDao.deleteFavoriteArtist(artistId)
            } else {
                libraryMetadataDao.upsertFavoriteArtist(
                    FavoriteArtistEntity(
                        artistId = artistId,
                        createdAt = System.currentTimeMillis()
                    )
                )
            }
            !isFavorite
        }
    }

    // --- PLAY HISTORY ---
    suspend fun recordSongPlay(songId: Long) = withContext(Dispatchers.IO) {
        database.withTransaction {
            val history = libraryMetadataDao.getPlayHistory(songId)
            val now = System.currentTimeMillis()
            if (history == null) {
                libraryMetadataDao.upsertPlayHistory(
                    PlayHistoryEntity(songId = songId, lastPlayedAt = now, playCount = 1)
                )
            } else {
                libraryMetadataDao.upsertPlayHistory(
                    history.copy(lastPlayedAt = now, playCount = history.playCount + 1)
                )
            }
        }
    }

    fun observeRecentSongs(limit: Int): Flow<List<Song>> {
        return libraryMetadataDao.observeRecentSongs(limit).map { ids ->
            val songs = librarySongs.value
            ids.mapNotNull { id -> songs.find { it.id == id } }
        }
    }

    fun observeTopSongs(limit: Int): Flow<List<Song>> {
        return libraryMetadataDao.observeTopSongs(limit).map { ids ->
            val songs = librarySongs.value
            ids.mapNotNull { id -> songs.find { it.id == id } }
        }
    }

    suspend fun createPlaylist(
        name: String,
        artworkSourceUri: Uri
    ): String = withContext(Dispatchers.IO) {
        val trimmedName = name.trim()
        require(trimmedName.isNotEmpty()) { "Playlist name cannot be blank." }

        val playlistId = USER_PLAYLIST_ID_PREFIX + UUID.randomUUID().toString()
        val now = System.currentTimeMillis()
        val persistedArtworkUri = persistPlaylistArtwork(
            playlistId = playlistId,
            sourceUri = artworkSourceUri
        ) ?: error("Unable to persist playlist artwork.")

        libraryMetadataDao.upsertPlaylist(
            PlaylistEntity(
                id = playlistId,
                name = trimmedName,
                type = USER_PLAYLIST_TYPE,
                artworkUri = persistedArtworkUri,
                createdAt = now,
                updatedAt = now
            )
        )
        playlistId
    }

    suspend fun deletePlaylist(playlistId: String) = withContext(Dispatchers.IO) {
        database.withTransaction {
            val playlist = libraryMetadataDao.getPlaylistById(playlistId)
            if (playlist?.type == USER_PLAYLIST_TYPE) {
                // Delete artwork file if it exists
                playlist.artworkUri?.let { uriStr ->
                    runCatching {
                        val uri = Uri.parse(uriStr)
                        if (uri.scheme == "file") {
                            File(uri.path ?: "").delete()
                        }
                    }
                }
                libraryMetadataDao.deletePlaylistSongs(playlistId)
                libraryMetadataDao.deletePlaylist(playlistId)
            }
        }
    }

    suspend fun updatePlaylist(
        id: String,
        name: String,
        artworkSourceUri: Uri?
    ) = withContext(Dispatchers.IO) {
        val playlist = libraryMetadataDao.getPlaylistById(id) ?: return@withContext
        if (playlist.type != USER_PLAYLIST_TYPE) return@withContext

        val trimmedName = name.trim()
        require(trimmedName.isNotEmpty()) { "Playlist name cannot be blank." }

        val now = System.currentTimeMillis()
        var newArtworkUri = playlist.artworkUri

        if (artworkSourceUri != null) {
            // Delete old artwork if it was a file
            playlist.artworkUri?.let { oldUriStr ->
                runCatching {
                    val oldUri = Uri.parse(oldUriStr)
                    if (oldUri.scheme == "file") {
                        File(oldUri.path ?: "").delete()
                    }
                }
            }
            newArtworkUri = persistPlaylistArtwork(id, artworkSourceUri)
        }

        libraryMetadataDao.updatePlaylist(
            playlistId = id,
            name = trimmedName,
            artworkUri = newArtworkUri,
            updatedAt = now
        )
    }

    suspend fun addSongToPlaylist(
        playlistId: String,
        songId: Long
    ): Boolean = withContext(Dispatchers.IO) {
        database.withTransaction {
            val playlist = libraryMetadataDao.getPlaylistById(playlistId) ?: return@withTransaction false
            if (playlist.type != USER_PLAYLIST_TYPE) return@withTransaction false
            if (libraryMetadataDao.playlistContainsSong(playlistId, songId)) return@withTransaction false

            val now = System.currentTimeMillis()
            libraryMetadataDao.upsertPlaylistSongs(
                listOf(
                    PlaylistSongEntity(
                        playlistId = playlistId,
                        songId = songId,
                        addedAt = now
                    )
                )
            )
            libraryMetadataDao.touchPlaylist(playlistId, now)
            true
        }
    }

    suspend fun removeSongFromPlaylist(
        playlistId: String,
        songId: Long
    ): Boolean = withContext(Dispatchers.IO) {
        database.withTransaction {
            val playlist = libraryMetadataDao.getPlaylistById(playlistId) ?: return@withTransaction false
            if (playlist.type != USER_PLAYLIST_TYPE && playlistId != LIKED_SONGS_PLAYLIST_ID) {
                return@withTransaction false
            }

            if (playlistId == LIKED_SONGS_PLAYLIST_ID) {
                if (!libraryMetadataDao.isSongFavorite(songId)) return@withTransaction false
                libraryMetadataDao.deleteFavoriteSong(songId)
            } else {
                if (!libraryMetadataDao.playlistContainsSong(playlistId, songId)) return@withTransaction false
                libraryMetadataDao.deletePlaylistSong(playlistId, songId)
            }

            libraryMetadataDao.touchPlaylist(playlistId, System.currentTimeMillis())
            true
        }
    }

    fun playlistIdsContainingSong(songId: Long): Flow<Set<String>> {
        return playlistSongEntities.asStateFlow().map { entries ->
            entries.asSequence()
                .filter { it.songId == songId }
                .map { it.playlistId }
                .toSet()
        }
    }

    suspend fun hideSong(songId: Long): Boolean = withContext(Dispatchers.IO) {
        val settings = MediaScannerPreferences.getSettings(context)
        if (songId in settings.blockedSongIds) return@withContext false

        database.withTransaction {
            if (libraryMetadataDao.isSongFavorite(songId)) {
                libraryMetadataDao.deleteFavoriteSong(songId)
            }
            libraryMetadataDao.deletePlaylistEntriesBySongId(songId)
        }

        MediaScannerPreferences.saveSettings(
            context = context,
            settings = settings.copy(
                blockedSongIds = settings.blockedSongIds + songId
            )
        )
        refreshLibrarySongs(force = true)
        true
    }

    fun getSongsForPlaylist(playlistId: String): Flow<List<Song>> {
        return combine(
            librarySongsFlow,
            favoriteSongIdsFlow,
            playlistSongEntities.asStateFlow()
        ) { songs, favoriteSongs, playlistEntries ->
            when (playlistId) {
                LIKED_SONGS_PLAYLIST_ID -> songs.filter { it.id in favoriteSongs }
                else -> {
                    val orderedSongIds = playlistEntries
                        .asSequence()
                        .filter { it.playlistId == playlistId }
                        .sortedByDescending { it.addedAt }
                        .map { it.songId }
                        .toList()

                    if (orderedSongIds.isEmpty()) {
                        emptyList()
                    } else {
                        val songsById = songs.associateBy { it.id }
                        orderedSongIds.mapNotNull(songsById::get)
                    }
                }
            }
        }
    }

    suspend fun getAlbumIdForArtist(artistId: Long): Long? = withContext(Dispatchers.IO) {
        mediaStore.getAlbumIdForArtist(artistId)
    }

    suspend fun getLastScannedSourceSongs(): List<Song> = withContext(Dispatchers.IO) {
        val inMemory = lastScannedSourceSongs.value
        if (inMemory.isNotEmpty()) return@withContext inMemory
        mediaStore.getSongs()
    }

    suspend fun ensureLibrarySongsLoaded() = withContext(Dispatchers.IO) {
        bootstrapFromLocalCache()
        if (!mediaStoreSyncDone) {
            refreshLibrarySongs(force = true)
        }
    }

    suspend fun refreshLibrarySongs() = withContext(Dispatchers.IO) {
        refreshLibrarySongs(force = true)
    }

    private suspend fun refreshLibrarySongs(force: Boolean) {
        refreshMutex.withLock {
            if (!force && !mediaStoreSyncDone) return@withLock

            if (!hasAudioReadPermission()) {
                clearLocalCache()
                mediaStoreSyncDone = true
                return@withLock
            }

            val settings = MediaScannerPreferences.getSettings(context)
            val allSongs = mediaStore.getSongs()
            val filteredSongs = filterSongs(
                songs = allSongs,
                ignoreTempFolders = settings.ignoreTempFolders,
                ignoreShortAudios = settings.ignoreShortAudios,
                manuallyBlockedFolders = settings.blockedFolders,
                manuallyBlockedSongIds = settings.blockedSongIds
            )

            lastScannedSourceSongs.value = allSongs
            syncSongsIncrementally(filteredSongs)
            mediaStoreSyncDone = true
        }
    }

    private suspend fun syncSongsIncrementally(newSongs: List<Song>) {
        val incomingEntities = newSongs.map { it.toEntity() }
        val incomingIds = incomingEntities.mapTo(mutableSetOf()) { it.id }

        val currentEntities = songCacheDao.getSongs()
        val currentById = currentEntities.associateBy { it.id }

        val toUpsert = incomingEntities.filter { incoming ->
            currentById[incoming.id] != incoming
        }
        val toDeleteIds = currentById.keys.filterNot { incomingIds.contains(it) }

        database.withTransaction {
            if (toUpsert.isNotEmpty()) {
                songCacheDao.upsertSongs(toUpsert)
            }
            if (toDeleteIds.isNotEmpty()) {
                songCacheDao.deleteSongsByIds(toDeleteIds)
            }
        }

        librarySongs.value = sortSongs(newSongs)
    }

    private suspend fun clearLocalCache() {
        database.withTransaction {
            songCacheDao.clearAllSongs()
        }
        librarySongs.value = emptyList()
        lastScannedSourceSongs.value = emptyList()
    }

    private fun observeLocalCache() {
        repositoryScope.launch {
            songCacheDao.observeSongs().collectLatest { entities ->
                librarySongs.value = entities.map { it.toDomain() }
                cacheBootstrapDone = true
            }
        }
    }

    private fun observeLibraryMetadata() {
        repositoryScope.launch {
            libraryMetadataDao.observeFavoriteSongIds().collectLatest { ids ->
                favoriteSongIds.value = ids.toSet()
            }
        }
        repositoryScope.launch {
            libraryMetadataDao.observeFavoriteAlbumIds().collectLatest { ids ->
                favoriteAlbumIds.value = ids.toSet()
            }
        }
        repositoryScope.launch {
            libraryMetadataDao.observeFavoriteArtistIds().collectLatest { ids ->
                favoriteArtistIds.value = ids.toSet()
            }
        }
        repositoryScope.launch {
            libraryMetadataDao.observePlaylists().collectLatest { entities ->
                playlistEntities.value = entities
            }
        }
        repositoryScope.launch {
            libraryMetadataDao.observePlaylistSongs().collectLatest { entities ->
                playlistSongEntities.value = entities
            }
        }
        repositoryScope.launch {
            combine(playlistEntities, playlistSongEntities, favoriteSongIds, librarySongs) { entities, playlistSongs, favoriteSongs, songs ->
                val visibleLikedSongs = songs.count { it.id in favoriteSongs }
                val visibleSongIds = songs.mapTo(mutableSetOf(), Song::id)
                val playlistSongCounts = playlistSongs
                    .groupBy { it.playlistId }
                    .mapValues { (_, entries) ->
                        entries.count { entry -> entry.songId in visibleSongIds }
                    }

                entities.map { entity ->
                    entity.toDomain(
                        likedSongCount = visibleLikedSongs,
                        playlistSongCount = playlistSongCounts[entity.id] ?: 0
                    )
                }
            }.collectLatest { currentPlaylists ->
                playlists.value = currentPlaylists
            }
        }
    }

    private suspend fun bootstrapFromLocalCache() {
        if (cacheBootstrapDone) return
        val cached = songCacheDao.getSongs().map { it.toDomain() }
        librarySongs.value = cached
        cacheBootstrapDone = true
    }

    private suspend fun ensureLikedSongsPlaylist(now: Long) {
        if (libraryMetadataDao.getPlaylistById(LIKED_SONGS_PLAYLIST_ID) != null) return
        libraryMetadataDao.upsertPlaylist(
            PlaylistEntity(
                id = LIKED_SONGS_PLAYLIST_ID,
                name = LIKED_SONGS_PLAYLIST_NAME,
                type = LIKED_SONGS_PLAYLIST_TYPE,
                artworkUri = null,
                createdAt = now,
                updatedAt = now
            )
        )
    }

    private fun persistPlaylistArtwork(
        playlistId: String,
        sourceUri: Uri
    ): String? {
        return runCatching {
            val artworkDirectory = File(context.filesDir, PLAYLIST_ARTWORK_DIRECTORY).apply {
                mkdirs()
            }
            val artworkFile = File(artworkDirectory, "$playlistId.jpg")
            context.contentResolver.openInputStream(sourceUri)?.use { input ->
                artworkFile.outputStream().use { output -> input.copyTo(output) }
            } ?: return null
            Uri.fromFile(artworkFile).toString()
        }.getOrNull()
    }

    private fun registerMediaStoreObserver() {
        if (mediaStoreObserver != null) return

        val observer = object : ContentObserver(Handler(Looper.getMainLooper())) {
            override fun onChange(selfChange: Boolean) {
                scheduleStorageRefresh()
            }

            override fun onChange(selfChange: Boolean, uri: Uri?) {
                scheduleStorageRefresh()
            }
        }

        context.contentResolver.registerContentObserver(
            MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,
            true,
            observer
        )
        mediaStoreObserver = observer
    }

    private fun scheduleStorageRefresh() {
        pendingRefreshJob?.cancel()
        pendingRefreshJob = repositoryScope.launch {
            delay(MEDIASTORE_REFRESH_DEBOUNCE_MS)
            refreshLibrarySongs(force = true)
        }
    }

    private fun hasAudioReadPermission(): Boolean {
        val permission = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            Manifest.permission.READ_MEDIA_AUDIO
        } else {
            Manifest.permission.READ_EXTERNAL_STORAGE
        }
        return ContextCompat.checkSelfPermission(context, permission) == PackageManager.PERMISSION_GRANTED
    }

    private fun filterSongs(
        songs: List<Song>,
        ignoreTempFolders: Boolean,
        ignoreShortAudios: Boolean,
        manuallyBlockedFolders: Set<String>,
        manuallyBlockedSongIds: Set<Long>
    ): List<Song> {
        return songs.filter { song ->
            val blockedTemp = ignoreTempFolders && song.path.isTempFolderPath()
            val blockedShort = ignoreShortAudios && song.duration < MIN_AUDIO_DURATION_MS
            val blockedManualFolder = manuallyBlockedFolders.contains(song.folderPath())
            val blockedManualSong = manuallyBlockedSongIds.contains(song.id)
            !(blockedTemp || blockedShort || blockedManualFolder || blockedManualSong)
        }
    }

    private fun sortSongs(songs: List<Song>): List<Song> {
        return songs.sortedWith(compareBy<Song> { it.title.lowercase() }.thenBy { it.id })
    }

    private fun String.isTempFolderPath(): Boolean {
        val normalized = lowercase()
        return TEMP_FOLDER_PATTERNS.any { normalized.contains(it) }
    }

    private fun Song.folderPath(): String {
        val normalized = path.replace('\\', '/')
        return normalized.substringBeforeLast('/', missingDelimiterValue = normalized)
    }

    companion object {
        const val LIKED_SONGS_PLAYLIST_ID = "liked_songs"
        const val LIKED_SONGS_PLAYLIST_TYPE = "auto_liked_songs"
        const val USER_PLAYLIST_TYPE = "user_created"
        private const val LIKED_SONGS_PLAYLIST_NAME = "Tus me gusta"
        private const val USER_PLAYLIST_ID_PREFIX = "playlist_"
        private const val PLAYLIST_ARTWORK_DIRECTORY = "playlist_artwork"
        private const val MIN_AUDIO_DURATION_MS = 60_000L
        private const val DISCOVERY_BATCH_SIZE = 12
        private const val MEDIASTORE_REFRESH_DEBOUNCE_MS = 650L
        private val TEMP_FOLDER_PATTERNS = listOf(
            "/whatsapp/",
            "/telegram/",
            "/cache/",
            "/temp/",
            "/tmp/"
        )
    }
}

private fun PlaylistEntity.toDomain(
    likedSongCount: Int,
    playlistSongCount: Int
): Playlist {
    return Playlist(
        id = id,
        name = name,
        songCount = if (type == MusicRepository.LIKED_SONGS_PLAYLIST_TYPE) likedSongCount else playlistSongCount,
        isAutoGenerated = type == MusicRepository.LIKED_SONGS_PLAYLIST_TYPE,
        artworkUri = artworkUri?.let { uriStr ->
            // Cache busting: append timestamp to ensure Coil reloads if file changed
            Uri.parse("$uriStr?t=$updatedAt")
        },
        updatedAt = updatedAt
    )
}
